apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: react-topology-ujs8
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: react-topology-ujs8
    app.kubernetes.io/part-of: my-test-app
  name: react-topology-ujs8
spec:
  ports:
  - port: 3001
    targetPort: 3001
  selector:
    app.kubernetes.io/instance: react-topology-ujs8
status:
  loadBalancer: {}
